name: Build

on:
  workflow_dispatch:
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out Git Repo
        uses: actions/checkout@v3
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Modules
        run: npm i

      - name: Build
        run: npm run build

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
        env: 
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
